imports:
    - { resource: '../common/config.yml' }
    - { resource: 'parameters.yml' }

vtex_api:
   base_uri:             'https://SUALOJA.vtexcommercestable.com.br'
   auth:
        app_key:              'USUARIO_DEV'
        app_secret:           'SENHA_DEV'

monolog:
    handlers:
        applog:
            type: stream
            path: /var/log/symfony.log
            level: error
        main:
            type: fingers_crossed
            action_level: warning
            handler: file
        file:
            type: stream
            level: debug
        syslog:
            type: syslog
            level: error
        doctrine:
            action_level: debug
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%_doctrine.log
            channels: doctrine