parameters:
    kernel.secret: sJvc3X0LYiTU
    database_driver:    pdo_mysql
    database_host:      127.0.0.1
    database_name:      painel
    database_user:      root
    database_password:  root
